[package]
name = "collider-cmd-start"
version = "0.1.0"
authors = ["Kat MarchÃ¡n <kzm@zkat.tech>"]
edition = "2018"

[dependencies]
collider-command = { path = "../../crates/collider-command" }
collider-common = { path = "../../crates/collider-common" }
